name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  update-er:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup mermerd
        run: |
          url=$(gh api /repos/KarnerTh/mermerd/releases -q '[.[] | select(.prerelease | not) | .assets[] | select(.name | contains("linux_amd64")) | .browser_download_url][0]')
          curl -fsSL "$url" | tar -zxf - mermerd
          chmod a+x ./mermerd
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin
          git switch chore/update-er-from-${{ github.ref_name }} 2>/dev/null || git switch -c chore/update-er-from-${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}
          echo 'XXXXX' >> ./tmp.txt
          git add tmp.txt
          git commit -m "Add tmp.txt"
          git push -u https://x-access-token:${GITHUB_TOKEN}@github.com/ym19851201/actions_test 
          git branch
          git status
          git log --name-status
          gh pr create \
            -B tmp/test-actions \
            -t 'update ER ${{ steps.check_pr.outputs.message }}' \
            -b 'ER updated!' \
            -a ${{ github.actor }} \
            -H chore/update-er-from-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
