name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  install-mermerd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup mermerd
        run: |
          url=$(curl -fsSL "https://api.github.com/repos/KarnerTh/mermerd/releases" | jq -r '[.[] | select(.prerelease | not) | .assets[] | select(.name | contains("linux_amd64")) | .browser_download_url][0]')
          curl -fsSL "$url" | tar zxf - mermerd ./mermerd
          chmod a+x ./mermerd
      - name: Run mermerd
        run: ./mermerd
      - name: Commit
        run: |
          echo 'XXXXX' > ./tmp.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tmp.txt
          git commit -m "Add tmp.txt"
          git push -u origin ${{ github.ref_name }}
